# Generated by Django 5.2.4 on 2025-07-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("😄", "Happy"),
                            ("😐", "Neutral"),
                            ("😔", "Sad"),
                            ("😡", "Angry"),
                            ("😴", "Tired"),
                        ],
                        max_length=2,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
