# Generated by Django 5.2.4 on 2025-07-28 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodentry",
            name="date",
        ),
        migrations.AddField(
            model_name="moodentry",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="mood",
            field=models.CharField(max_length=100),
        ),
    ]
